sudo: false
language: rust
rust:
- nightly
- beta
- stable
env:
  global:
    - FEATURES=yaml_enc,bin_enc,ron_enc
script:
- |
  cargo build --features $FEATURES &&
  cargo test --features $FEATURES &&
  cargo doc --features $FEATURES
