[package]
authors = ["Marcel Müller <neikos@neikos.email>"]
description = "A single file database"
documentation = "http://neikos.me/rustbreak/rustbreak/index.html"
homepage = "https://github.com/TheNeikos/rustbreak"
keywords = ["database", "simple", "fast", "daybreak", "rustbreak"]
license = "MPL-2.0"
name = "rustbreak"
readme = "README.md"
repository = "https://github.com/TheNeikos/rustbreak"
version = "1.1.0"

[dependencies]
bincode = { version = "0.6", optional = true }
serde_yaml = { version = "0.6", optional = true }
fs2 = "0.4"
quick-error = "1.1.0"
serde = "0.8"

[dev-dependencies]
tempfile = "2.1"
lazy_static = "0.2.1"

[features]
default = ["bin"]
bin = ["bincode"]
yaml = ["serde_yaml"]
