[package]
authors = ["Marcel Müller <neikos@neikos.email>"]
description = "A single point database"
documentation = "http://neikos.me/rustbreak/rustbreak/index.html"
homepage = "https://github.com/TheNeikos/rustbreak"
keywords = ["database", "simple", "fast", "daybreak", "rustbreak"]
license = "MPL-2.0"
name = "rustbreak"
readme = "README.md"
repository = "https://github.com/TheNeikos/rustbreak"
version = "2.0.0"

[dependencies]
failure = "0.1.1"
ron = "0.2.0"
serde = "1"

[dependencies.base64]
optional = true
version = "0.9.0"

[dependencies.bincode]
optional = true
version = "1"

[dependencies.serde_yaml]
optional = true
version = "0.7"

[dev-dependencies]
lazy_static = "1"
serde_derive = "1"
tempfile = "3.0.0"

[features]
bin = ["bincode", "base64"]
yaml = ["serde_yaml"]
